### ISSUE TITLE
gafa_stock is irregular

### ISSUE THREAD

**Issue by robjhyndman** [tidyverts/tsibbledata#8]
I think `gafa_stock` should be daily, not irregular.

**Comment by robjhyndman** [comment]
The problem is that the following doesn't work:
```r
gafa_stock %>%
  filter(Symbol == "GOOG", year(Date) == 2015) %>%
  ACF(Close)
```

**Comment by mitchelloharawild** [comment]
If it's daily, then ACF would fail because it contains implicit missing values. If we're looking to make gafa_stock work with functions without any user input, we would require a "trading day" index, rather than a date index.

*CF, decompositions and modelling are sensitive to the time index, and so lags are done respective to the interval. This is not what we want for stock data, as we want to lag by the trading day (is this correct? or should non-trading days be treated as missing?).

The incompatibility with implicit missing values and modelling will become more apparent once https://github.com/tidyverts/fable/issues/106 is implemented.

**Comment by mitchelloharawild** [comment]
``` r
library(feasts)
library(tsibbledata)
#> Loading required package: tsibble
#> 
#> Attaching package: 'tsibble'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
library(lubridate)
#> 
#> Attaching package: 'lubridate'
#> The following objects are masked from 'package:tsibble':
#> 
#>     interval, new_interval
#> The following object is masked from 'package:base':
#> 
#>     date

gafa_stock %>%
  filter(Symbol == "GOOG", year(Date) == 2015) %>%
  ACF(Close)
#> Error: Can't handle tsibble of irregular interval.

gafa_stock %>%
  filter(Symbol == "GOOG", year(Date) == 2015) %>%
  mutate(trading_day = row_number()) %>% 
  update_tsibble(index = trading_day, regular = TRUE) %>% 
  ACF(Close)
#> # A tsibble: 24 x 3 [1]
#> # Key:       Symbol [1]
#>    Symbol   lag   acf
#>    <fct>  <lag> <dbl>
#>  1 GOOG       1 0.982
#>  2 GOOG       2 0.959
#>  3 GOOG       3 0.937
#>  4 GOOG       4 0.918
#>  5 GOOG       5 0.901
#>  6 GOOG       6 0.883
#>  7 GOOG       7 0.865
#>  8 GOOG       8 0.849
#>  9 GOOG       9 0.834
#> 10 GOOG      10 0.818
#> # … with 14 more rows
```

<sup>Created on 2019-03-11 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by mitchelloharawild** [comment]
Also, if gafa_stock were to be treated as regular, there would need to be another irregular time series to replace it. I think it's useful to show how an irregular time series can be made regular, and note the strong implications that this has.

**Comment by robjhyndman** [comment]
Yes, ok.
